### ISSUE TITLE
Code Linting

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#23]
Use the [lint package](https://pub.dev/packages/lint) to add linting rules in the project.

**Comment by aayushbisen** [comment]
I can work on this.

**Comment by himanshusharma89** [comment]
@aayushbisen Are you participating in GSSOC? If so, I'll assign this issue to you.

**Comment by aayushbisen** [comment]
Yes I am participating.

**Comment by aayushbisen** [comment]
Added the linter, should I fix the warnings also? About 271 are there as of now.

**Comment by himanshusharma89** [comment]
@aayushbisen can you add the rules image here? And yes you need to resolve those issues and warnings, that’s why it is an advance issue.

**Comment by aayushbisen** [comment]
![image](https://user-images.githubusercontent.com/41341387/110425940-3886b200-80cb-11eb-923b-189eb25179d8.png)

I didn't add any custon rules yet, just default config that comes with lint package.

**Comment by himanshusharma89** [comment]
You need to add some rules also, I’ll share them with you, in the mean time, you can resolve all these warning

**Comment by aayushbisen** [comment]
Okay

**Comment by himanshusharma89** [comment]
@aayushbisen Add these linter rules:
```yaml
# https://dart-lang.github.io/linter/lints/

# Not happy with the default? Customize the rules depending on your needs. 
# Here are some examples:
linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    # public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true
    prefer_const_constructors: true
    prefer_const_declarations: true
```
